# Generated by Django 5.2.6 on 2025-12-20 08:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='start_date',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='from_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='to_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='reason',
            field=models.TextField(blank=True),
        ),
    ]
